### ISSUE TITLE
Code Segments Render on One Line

### ISSUE THREAD

**Issue by nikhiljha** [philhawksworth/eleventyone#13]
See here: https://eleventyone.netlify.com/posts/a-post/

**Comment by nikhiljha** [comment]
Something I did here fixed it: https://github.com/nikhiljha/blog/commit/278405d08b63a6d236b28c691733b6d10dc46868

**Comment by philhawksworth** [comment]
I'm not seeing this issue.
looks to have been resolved in subsequent updates.
