### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by jamesplease** [philhawksworth/eleventyone#23]
I hope you don't mind me opening an issue for this, but I just wanted to stop by to say **thank you**! I've been loving Eleventy, but I found myself having some questions that I couldn't find answers for in the docs, such as CSS concatenation while still supporting live reloading. Referencing this project has been a _huge_ help to me.

So...THANK YOU 😁

**Comment by philhawksworth** [comment]
Oh that's terribly kind of you.
I initially made this for myself, but am glad that sharing it has been useful for some.
Many thanks!
