### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jamesplease** [philhawksworth/eleventyone#25]
Hi @philhawksworth ! Would you mind adding a license file to this project? 🙏 ty!

**Comment by d2s** [comment]
EleventyOne is MIT licensed.

`package.json` lists it on the line 6:
https://github.com/philhawksworth/eleventyone/blob/67f0be3f17b6cbc1f2306983e3ce460967dbe58c/package.json#L6

Separate text file for the license would certainly be useful addition, though,
as it would display the license directly on the repository level.

**Comment by philhawksworth** [comment]
Good catch. Added a License file to make it clear that this is MIT

**Comment by jamesplease** [comment]
thank you, @philhawksworth !
