### ISSUE TITLE
Suggestion: add more instructions for getting started locally

### ISSUE THREAD

**Issue by edwardhorsford** [philhawksworth/eleventyone#3]
I've just given this a try (using the add to netlify command).

I feel it could do with a bit more instruction for getting it to run locally.

I presume some form of:
```
npm install
npx eleventy
```

**Comment by DirtyF** [comment]
or point to https://www.11ty.io/docs/local-installation/ 😄

**Comment by michalzadkowski** [comment]
Ugh, yes please. I'm struggling to get a grip with it all as well.
I'm pretty confused as to what goes where and which files serve what purpose.

**Comment by philhawksworth** [comment]
oooh, the instructions have been around for a while. Hoping those were useful and closing this old issue.
